import _ from "lodash";
import { BankType } from './bankTypes';
const config = {
  all: {
    env: process.env.REACT_APP_STAGE || "USBANK_DEV",
    baseName: process.env.PUBLIC_URL,
    sessionTimeout: 1000 * 5 * 12 * 20, //20 min
    showPopupTime: 1000 * 5 * 12 * 1, //1 min
    bankTypeId: BankType.USBANK,
  },
  uat: {
    willTranslate: true,
    showCaptcha: false,
    disableContextMenu: false,
    apiBase: "https://apib2b.incedopay.com:30010/api",
    baseURL: `${window.location.protocol}//${window.location.hostname}:${window.location.port}`,
    notificationSocket: "https://apib2b.incedopay.com:30010",
    consumerService:
      "https://apib2b.incedopay.com:30010/api/consumer-service/v1",
    masterCardService:
      "https://apib2b.incedopay.com:30010/api/mastercard-service",
    paymentService: "https://apib2b.incedopay.com:30010/api/payment-service",
    clientConfigService: "https://apib2b.incedopay.com:30010/api/client-config-service/v1",
    userService: "https://apib2b.incedopay.com:30010/api/user-service/v1",
    clientService: "https://apib2b.incedopay.com:30010/api/client-service/v1",
    notificationService: "https://apib2b.incedopay.com:30010/api/notification-service/v1",
    payeeService: "https://apib2b.incedopay.com:30010/api/payee-service/v1",
    bankTypeId: BankType.CITIBANK,
    apiVersion: 'v1',
  },
  CITI_UAT: {
    willTranslate: true,
    showCaptcha: false,
	disableContextMenu: false,
    apiBase: "https://citib2bapi.incedopay.com/api",
    baseURL: `${window.location.protocol}//${window.location.hostname}:${window.location.port}`,
    notificationSocket: "https://citib2bapi.incedopay.com",
    consumerService: "https://citib2bapi.incedopay.com/api/consumer-service/v1",
    masterCardService:
      "https://citib2bapi.incedopay.com/api/mastercard-service",
    paymentService: "https://citib2bapi.incedopay.com/api/payment-service",
    clientConfigService: "https://citib2bapi.incedopay.com/api/client-config-service/v1",
    userService: "https://citib2bapi.incedopay.com/api/user-service/v1",
    clientService: "https://citib2bapi.incedopay.com/api/client-service/v1",
    notificationService: "https://citib2bapi.incedopay.com/api/notification-service/v1",
    payeeService: "https://citib2bapi.incedopay.com/api/payee-service/v1",
    bankTypeId: BankType.CITIBANK,
    apiVersion: 'v1',
  },
  CITI_CTE: {
    willTranslate: true,
    showCaptcha: true,
	disableContextMenu: false,
    apiBase:
      "https://b2bapi.paymentexchange.cte.transactionservices.citi.com/api",
    baseURL: `${window.location.protocol}//${window.location.hostname}:${window.location.port}`,
    notificationSocket:
      "https://b2bapi.paymentexchange.cte.transactionservices.citi.com",
    consumerService:
      "https://b2bapi.paymentexchange.cte.transactionservices.citi.com/api/consumer-service/v1",
    masterCardService:
      "https://b2bapi.paymentexchange.cte.transactionservices.citi.com/api/mastercard-service",
    paymentService:
      "https://b2bapi.paymentexchange.cte.transactionservices.citi.com/api/payment-service",
    clientConfigService: 
      "https://b2bapi.paymentexchange.cte.transactionservices.citi.com/api/client-config-service/v1",
    userService: "https://b2bapi.paymentexchange.cte.transactionservices.citi.com/api/user-service/v1",
    clientService: "https://b2bapi.paymentexchange.cte.transactionservices.citi.com/api/client-service/v1",
    notificationService: "https://b2bapi.paymentexchange.cte.transactionservices.citi.com/api/notification-service/v1",
    payeeService: "https://b2bapi.paymentexchange.cte.transactionservices.citi.com/api/payee-service/v1",
    bankTypeId: BankType.CITIBANK,
    apiVersion: 'v1',
  },
  CITI_PROD: {
    willTranslate: true,
    showCaptcha: true,
	disableContextMenu: true,
    apiBase: "https://b2bapi.citipaymentexchange.citi.com/api",
    baseURL: `${window.location.protocol}//${window.location.hostname}:${window.location.port}`,
    notificationSocket: "https://b2bapi.citipaymentexchange.citi.com",
    consumerService:
      "https://b2bapi.citipaymentexchange.citi.com/api/consumer-service/v1",
    masterCardService:
      "https://b2bapi.citipaymentexchange.citi.com/api/mastercard-service",
    paymentService:
      "https://b2bapi.citipaymentexchange.citi.com/api/payment-service",
    clientConfigService: "https://b2bapi.citipaymentexchange.citi.com/api/client-config-service/v1",
    userService: "https://b2bapi.citipaymentexchange.citi.com/api/user-service/v1",
    clientService: "https://b2bapi.citipaymentexchange.citi.com/api/client-service/v1",
    notificationService: "https://b2bapi.citipaymentexchange.citi.com/api/notification-service/v1",
    payeeService: "https://b2bapi.citipaymentexchange.citi.com/api/payee-service/v1",
    bankTypeId: BankType.CITIBANK,
    apiVersion: 'v1',
  },
  CITI_DR: {
    willTranslate: true,
    showCaptcha: true,
	disableContextMenu: false,
    apiBase: "https://b2bapi.citipaymentexchange.citi.com/api",
    baseURL: `${window.location.protocol}//${window.location.hostname}:${window.location.port}`,
    notificationSocket: "https://b2bapi.citipaymentexchange.citi.com",
    consumerService:
      "https://b2bapi.citipaymentexchange.citi.com/api/consumer-service/v1",
    masterCardService:
      "https://b2bapi.citipaymentexchange.citi.com/api/mastercard-service",
    paymentService:
      "https://b2bapi.citipaymentexchange.citi.com/api/payment-service",
    clientConfigService: "https://b2bapi.citipaymentexchange.citi.com/api/client-config-service/v1",
    userService: "https://b2bapi.citipaymentexchange.citi.com/api/user-service/v1",
    clientService: "https://b2bapi.citipaymentexchange.citi.com/api/client-service/v1",
    notificationService: "https://b2bapi.citipaymentexchange.citi.com/api/notification-service/v1",
    payeeService: "https://b2bapi.citipaymentexchange.citi.com/api/payee-service/v1",
    bankTypeId: BankType.CITIBANK,
    apiVersion: 'v1',
  },
  USBANK_DEV: {
    willTranslate: true,
    showCaptcha: true,
    disableContextMenu: false,
    apiBase: "https://b2cusbankapi.incedopay.com:30010/api",
    baseURL: `${window.location.protocol}//${window.location.hostname}:${window.location.port}`,
    notificationSocket: "https://b2cusbankapi.incedopay.com:30010",
    consumerService:"https://b2cusbankapi.incedopay.com:30010/api/consumer-service/v2",
    masterCardService:"https://b2cusbankapi.incedopay.com:30010/api/mastercard-service",
    paymentService: "https://b2cusbankapi.incedopay.com:30010/api/payment-service/v2",
    clientConfigService: "https://b2cusbankapi.incedopay.com:30010/api/client-config-service/v2",
    userService: "https://b2cusbankapi.incedopay.com:30010/api/user-service/v2",
    clientService: "https://b2cusbankapi.incedopay.com:30010/api/client-service/v2",
    notificationService: "https://b2cusbankapi.incedopay.com:30010/api/notification-service/v2",
    payeeService: "https://b2cusbankapi.incedopay.com:30010/api/payee-service/v2",
    bankTypeId: BankType.USBANK,
    apiVersion: 'v2',
  },
  US_UAT: {
    willTranslate: true,
    showCaptcha: true,
    disableContextMenu: false,
    apiBase: "https://b2cusbankapiuat.incedopay.com:30010/api",
    baseURL: `${window.location.protocol}//${window.location.hostname}:${window.location.port}`,
    notificationSocket: "https://b2cusbankapiuat.incedopay.com:30010",
    consumerService:"https://b2cusbankapiuat.incedopay.com:30010/api/consumer-service/v2",
    masterCardService:"https://b2cusbankapiuat.incedopay.com:30010/api/mastercard-service",
    paymentService: "https://b2cusbankapiuat.incedopay.com:30010/api/payment-service/v2",
    clientConfigService: "https://b2cusbankapiuat.incedopay.com:30010/api/client-config-service/v2",
    userService: "https://b2cusbankapiuat.incedopay.com:30010/api/user-service/v2",
    clientService: "https://b2cusbankapiuat.incedopay.com:30010/api/client-service/v2",
    notificationService: "https://b2cusbankapiuat.incedopay.com:30010/api/notification-service/v2",
    payeeService: "https://b2cusbankapiuat.incedopay.com:30010/api/payee-service/v2",
    bankTypeId: BankType.USBANK,
    apiVersion: 'v2',
  },
  US_QC: {
    willTranslate: true,
    showCaptcha: true,
    disableContextMenu: false,
    apiBase: "https://b2cusbankapiqc.incedopay.com:30010/api",
    baseURL: `${window.location.protocol}//${window.location.hostname}:${window.location.port}`,
    notificationSocket: "https://b2cusbankapiqc.incedopay.com:30010",
    consumerService:"https://b2cusbankapiqc.incedopay.com:30010/api/consumer-service/v2",
    masterCardService:"https://b2cusbankapiqc.incedopay.com:30010/api/mastercard-service",
    paymentService: "https://b2cusbankapiqc.incedopay.com:30010/api/payment-service/v2",
    clientConfigService: "https://b2cusbankapiqc.incedopay.com:30010/api/client-config-service/v2",
    userService: "https://b2cusbankapiqc.incedopay.com:30010/api/user-service/v2",
    clientService: "https://b2cusbankapiqc.incedopay.com:30010/api/client-service/v2",
    notificationService: "https://b2cusbankapiqc.incedopay.com:30010/api/notification-service/v2",
    payeeService: "https://b2cusbankapiqc.incedopay.com:30010/api/payee-service/v2",
    bankTypeId: BankType.USBANK,
    apiVersion: 'v2',
  },
  US_PREPROD: {
    willTranslate: true,
    showCaptcha: true,
    disableContextMenu: false,
    apiBase: "https://b2cusbankapipreprod.incedopay.com:30010/api",
    baseURL: `${window.location.protocol}//${window.location.hostname}:${window.location.port}`,
    notificationSocket: "https://b2cusbankapipreprod.incedopay.com:30010",
    consumerService:"https://b2cusbankapipreprod.incedopay.com:30010/api/consumer-service/v2",
    masterCardService:"https://b2cusbankapipreprod.incedopay.com:30010/api/mastercard-service",
    paymentService: "https://b2cusbankapipreprod.incedopay.com:30010/api/payment-service/v2",
    clientConfigService: "https://b2cusbankapipreprod.incedopay.com:30010/api/client-config-service/v2",
    userService: "https://b2cusbankapipreprod.incedopay.com:30010/api/user-service/v2",
    clientService: "https://b2cusbankapipreprod.incedopay.com:30010/api/client-service/v2",
    notificationService: "https://b2cusbankapipreprod.incedopay.com:30010/api/notification-service/v2",
    payeeService: "https://b2cusbankapipreprod.incedopay.com:30010/api/payee-service/v2",
    bankTypeId: BankType.USBANK,
    apiVersion: 'v2',
  },
};

export default _.merge(config.all, config[config.all.env]);
